name: CI

on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - v0.0.*
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pre-commit
        python -m pip install --upgrade platformio
    - name: pre-commit
      run: |
        pre-commit run --all-files
    - name: Build PlatformIO Project
      run: pio run
    - name: Prepare variables to name the artifacts
      run: |
        echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Rename the artifacts
      run: |
        mkdir firmware
        for variant in $(cd .pio/build && echo *); do
          if [ -d .pio/build/$variant ]; then
            md5=$(md5sum .pio/build/$variant/firmware.bin | cut -d' ' -f1)
            if [ "${{github.event_name}}" = "pull_request" ]; then
              pr_number=$(echo -n ${{github.ref_name}} | cut -d/ -f1)
              cp .pio/build/$variant/firmware.bin firmware/toolman-${{env.TODAY}}-pr${pr_number}-${{env.SHORT_SHA}}-$variant-$md5.bin
              cp .pio/build/$variant/firmware.elf firmware/toolman-${{env.TODAY}}-pr${pr_number}-${{env.SHORT_SHA}}-$variant-$md5.elf
            elif [ "${{github.event_name}}" = "push" ]; then
              if [ "${{github.ref_type}}" = "tag" ]; then
                cp .pio/build/$variant/firmware.bin firmware/toolman-${{github.ref_name}}-$variant-$md5.bin
                cp .pio/build/$variant/firmware.elf firmware/toolman-${{github.ref_name}}-$variant-$md5.elf
              elif [ "${{github.ref_type}}" = "branch" ]; then
                ref_name=$(echo -n ${{github.ref_name}} | sed -e 's/[^A-Za-z0-9]/_/g')
                cp .pio/build/$variant/firmware.bin firmware/toolman-${{env.TODAY}}-${ref_name}-${{env.SHORT_SHA}}-$variant-$md5.bin
                cp .pio/build/$variant/firmware.elf firmware/toolman-${{env.TODAY}}-${ref_name}-${{env.SHORT_SHA}}-$variant-$md5.elf
              fi
            fi
          fi
        done
    - uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: firmware/

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware
      - name: Upload
        run: |
          for filename in *; do
            curl \
              -X PUT \
              --oauth2-bearer ${{secrets.ARTIFACT_KEY}} \
              --header "Content-Type: application/octet-stream" \
              --data-binary @$filename \
              --fail \
              ${{vars.ARTIFACT_URL}}/$filename
          done
        working-directory: firmware
